//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int HeroID { get; set; }
        public string HeroName { get; set; }
        public int HeroTypeID { get; set; }
        public System.DateTime AddData { get; set; }
        public string Picture { get; set; }
        public string HeroStory { get; set; }
    
        public virtual HeroType HeroType { get; set; }
    }
}
